;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				electric-newline-and-maybe-indent
				end-of-visual-line
				indent-for-tab-command
				keyboard-escape-quit
				org-end-of-line
				overwrite-mode
				sh-assignment
				yaml-electric-backspace
				yaml-electric-dash-and-dot
				beginning-of-visual-line
				))

(setq mc/cmds-to-run-once
      '(
				mouse-set-region
				))
