;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		electric-newline-and-maybe-indent
		beginning-of-visual-line
		end-of-visual-line
		indent-for-tab-command
		org-end-of-line
		sh-assignment
		yaml-electric-backspace
		yaml-electric-dash-and-dot
		))

(setq mc/cmds-to-run-once
      '(
				mouse-set-region
				))
