;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				beginning-of-visual-line
				c-electric-brace
				c-electric-colon
				c-electric-lt-gt
				c-electric-paren
				c-electric-pound
				c-electric-semi&comma
				c-electric-slash
				c-electric-star
				c-indent-line-or-region
				electric-newline-and-maybe-indent
				electric-verilog-colon
				electric-verilog-semi
				electric-verilog-tab
				electric-verilog-tick
				end-of-visual-line
				ignore
				indent-for-tab-command
				keyboard-escape-quit
				kmacro-start-macro-or-insert-counter
				markdown-cycle
				markdown-outdent-or-delete
				org-cycle
				org-end-of-line
				org-force-self-insert
				org-return-indent
				org-self-insert-command
				org-yank
				overwrite-mode
				puppet-interpolate
				sh-assignment
				smarter-move-beginning-of-line
				specman-activate-indent
				specman-insert-bracket-closer
				specman-insert-bracket-opener
				specman-insert-curly-closer
				specman-insert-gt
				specman-insert-parens-closer
				specman-insert-parens-opener
				specman-remove-tab
				tabbar-backward-tab
				tabbar-select-tab-callback
				typescript-insert-and-indent
				yaml-electric-backspace
				yaml-electric-dash-and-dot
				))

(setq mc/cmds-to-run-once
      '(
				handle-switch-frame
				kill-region
				mouse-set-region
				org-insert-heading-respect-content
				tabbar-forward-tab
				view-order-manuals
				))
